# -*- coding: utf-8 -*-
"""image processing task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14K4JV7PHSLsjrsNVujNifrT_Rvagb3w6
"""

import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow
ref=cv.imread('/content/ideal.jpg')
ref=cv.cvtColor(ref,cv.COLOR_BGR2GRAY)
ref=cv.GaussianBlur(ref,(5,5),0)
ret,ref=cv.threshold(ref,125,255,cv.THRESH_BINARY)
kernel = np.ones((5,5), np.uint8)
ref=cv.morphologyEx(ref,cv.MORPH_OPEN,kernel)
ref=cv.morphologyEx(ref,cv.MORPH_CLOSE,kernel)
refcontour,hierarchies=cv.findContours(ref,cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)

smp=cv.imread('/content/sample2.jpg')
smp=cv.cvtColor(smp,cv.COLOR_BGR2GRAY)
smp=cv.GaussianBlur(smp,(5,5),0)
ret,smp=cv.threshold(smp,125,255,cv.THRESH_BINARY)
kernel = np.ones((5,5), np.uint8)
smp=cv.morphologyEx(smp,cv.MORPH_OPEN,kernel)
smp=cv.morphologyEx(smp,cv.MORPH_CLOSE,kernel)
smpcontour,smphierarchies=cv.findContours(smp,cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)
cv2_imshow(smp)

inner_ref = sorted(refcontour, key=cv.contourArea)[0]
(ref_x ,ref_y), ideal= cv.minEnclosingCircle(inner_ref)

inner_smp = sorted(smpcontour, key=cv.contourArea)[0]
(smp_x, smp_y), rad = cv.minEnclosingCircle(inner_smp)
smp_contour = max(smpcontour,key=cv.contourArea)
smp_area=cv.contourArea(smp_contour)
white_area=cv.countNonZero(smp)
flag=0
if smp_area <= white_area:
  print("there is no hole")
  flag=1
if flag==0:
 rad=int(rad)
 ideal=int(ideal)
 #print(f"sample radius={rad}")
 #print(f"ideal radius={ideal}")

 if (rad - ideal) > 0.5:
   print("hole is bigger")
 elif (rad - ideal) < -0.5:
   print("hole is smaller")
 else:
   print("hole is perfect")

#missing teeth
missing=cv.bitwise_xor(smp,ref)
cir=cv.circle(missing,(int(smp_x),int(smp_y)),120,0,-1)
#cv2_imshow(missing)
kernel=np.ones((5,5),np.uint8)
missing=cv.morphologyEx(missing,cv.MORPH_OPEN,kernel)
missing=cv.morphologyEx(missing,cv.MORPH_CLOSE,kernel)
contours,hierarchies=cv.findContours(missing,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE)
broken=0
for i in contours:
 missing_area=cv.contourArea(i)

 if missing_area>10 :
  broken+=1

print(f"there are {broken} broken teeth")